name: phpcs

on: push

jobs:
  Code-Analysis: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install phpcs
        run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar
         
      - name: Check coding standards
        id: phpcs
        run: ./vendor/bin/phpcs --report=json  --report-file=report.json --standard=PSR2 --colors --encoding=utf-8 app
        
   
 